### ISSUE TITLE
serialize() fails with java.io.NotSerializableException: com.mbientlab.metawear.impl.JseMetaWearBoard$4

### ISSUE THREAD

**Issue by dominicjprice** [mbientlab/MetaWear-SDK-Android#10]
Hi, I'm getting the above error when trying to serialize the board state with version 3.0.7 of the api. Full stack trace follows.

`com.mbientlab.metawear.impl.JseMetaWearBoard$4
                                                             java.io.NotSerializableException: com.mbientlab.metawear.impl.JseMetaWearBoard$4
                                                                 at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                                                                 at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                 at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                                 at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                                 at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                                 at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                                 at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                 at java.util.HashMap.writeObject(HashMap.java:976)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
                                                                 at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                                 at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                 at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                                 at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                                 at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                                 at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                                 at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                 at com.mbientlab.metawear.impl.JseMetaWearBoard.serialize(JseMetaWearBoard.java:1052)
                                                                 at com.mbientlab.metawear.impl.JseMetaWearBoard.serialize(JseMetaWearBoard.java:1044)`

**Comment by scaryghost** [comment]
Post the API calls you are using prior to serialization

**Comment by dominicjprice** [comment]
Thanks, I've managed to solve the issue. I was setting a task to flash the led after disconnection before I was calling serialize() that was resulting in the above exception being thrown.

**Comment by scaryghost** [comment]
The API probably does not handle serializing an ``Observable`` correctly which it should.  That usage shouldn't cause a serialization error.

**Comment by scaryghost** [comment]
Fixed in v3.0.11.
