### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Queue.poll()' on a null object reference

### ISSUE THREAD

**Issue by dominicjprice** [mbientlab/MetaWear-SDK-Android#12]
Hi, getting the following exception when trying to set up a passthrough dataprocessor:

> Unhandled exception in callback
                                                                     java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Queue.poll()' on a null object reference
                                                                         at com.mbientlab.metawear.impl.DataProcessorImpl$2.onResponseReceived(DataProcessorImpl.java:138)
                                                                         at com.mbientlab.metawear.impl.JseMetaWearBoard$4.onMwNotifyCharChanged(JseMetaWearBoard.java:573)
                                                                         at com.mbientlab.metawear.android.BtleService$1.onCharacteristicChanged(BtleService.java:228)
                                                                         at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:438)
                                                                         at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:399)
                                                                         at android.os.Binder.execTransact(Binder.java:453)

I'm using version 3.0.17 of the SDK with the following code setting up the dataprocessor:
```java
acc.acceleration().addRouteAsync(new RouteBuilder() {
    @Override
    public void configure(RouteComponent source) {
        source.limit(Passthrough.CONDITIONAL, (short) 0)
              .name("acceleration_passthrough")
              .log(accelerationSubscriber);
        }
});

**Comment by scaryghost** [comment]
I cannot reproduce that error on my side.

* What Android device and OS are you using?  
* Can you successfully log the data without using the ``limit`` component?  
* Does the ``addRouteAsync`` task complete with a ``TimeoutException`` before the NPE is thrown?

**Comment by dominicjprice** [comment]
HI, I'm using a Nexus 5 and developing on Ubuntu with Android Studio 2.3. Interestingly, I haven't been able to look at it for a few days and now that I've come back to it with a fresh install, the exception is no longer occurring. I'll report back if anything similar occurs.
